### ISSUE TITLE
MaltegoCE on Menu does not work

### ISSUE THREAD

**Issue by knucker** [ArchStrike/ArchStrike#346]
I tried to start maltegoce via menu, but does not work.
I think the problem is that the archstrike-maltegoce.service call 'sh -c "mategoce"', but the executable is "maltego" not "maltegoce".

![1490882630](https://cloud.githubusercontent.com/assets/26332609/24508109/e2103060-1538-11e7-83e9-caa91dfc6009.png)

![1490883194](https://cloud.githubusercontent.com/assets/3603619/24508560/297460ce-153a-11e7-83da-e718f07e8c8c.png)

**Comment by xorond** [comment]
This issue should have been opened at [the menu repository](https://github.com/ArchStrike/archstrike-menu)

In any case, this has been fixed in https://github.com/ArchStrike/archstrike-menu/commit/fef629487561fd2394da3ce3b727603ad778b419 however it wasn't in the release version 1.0. I have made a new release, 1.1, and updated the version in the repository in https://github.com/ArchStrike/ArchStrike/commit/4c0ab2f8344553637543d5fa950416d4134021dc
It's being built now and should be soon in the repository.

**Comment by knucker** [comment]
Thank you.
And sorry about that.
