### ISSUE TITLE
Android SELinux Versus archstrike-installer

### ISSUE THREAD

**Issue by sdrausty** [ArchStrike/ArchStrike#411]
I tried to install `archstrike-installer` after installing [Arch Linux in Termux PRoot](https://sdrausty.github.io/TermuxArch/docs/install) on an Android smartphone.  This is a screenshot of the results from the device:

![screenshot_20180415-201053](https://user-images.githubusercontent.com/27742457/38785121-c6834322-40e9-11e8-90f4-9665367201cf.png)

Is this an Android SELinux limitation?  Suggestions regarding a solution or work around are welcome.

**Comment by xorond** [comment]
Hi, I think this is happening because it looks like android doesn't have `timedatectl`. The installer is intended to use on a regular Archlinux installation, so we're unable to guarantee that it will work with your setup.
If you wish, the code for the installer is on https://github.com/ArchStrike/archstrike-installer
You may edit the installation commands according to your setup. In the case you get it working, I'd be very pleased if you could PR the edited version which works on android.

**Comment by sdrausty** [comment]
Hi, @xorond thanks for the update and advice.  I'll be taking a closer look at this is when I have a little bit more time.  What brought me here (to make a long story short) is after finding a fairly stable Linux distribution that works on a smartphone in Android...  While promoting and refining the [Arch Linux in Termux PRoot](https://sdrausty.github.io/TermuxArch/) installation script [TermuxArch](https://github.com/sdrausty/TermuxArch/issues/59)  I fell upon the seamless installation of ArchStrike and BlackArch on a smartphone and tablet which is outlined in the installation instructions for those who want something more than vanilla Ach Linux in Termux PRoot on device.

A user posted a couple issues [regarding troubles with Archstrike](https://github.com/sdrausty/TermuxArch/issues/67).  While debugging I thought that this might be important; What is more, easily patchable.   Any idea why `sudo` does not work as expected?
