### ISSUE TITLE
MyServer [ Tool Request ]

### ISSUE THREAD

**Issue by Rajkumrdusad** [ArchStrike/ArchStrike#428]
Tool-Name :- MyServer
Version :- 1.0
Source :- https://github.com/Rajkumrdusad/MyServer

MyServer is used to start localhost and Database web server on linux.

Support :
- Apache2 web server
- Nginx web server
- PHP web server
- Python web server
- MySQL Database server

I hope MyServer is used to web development and testing of websites on system.
If this tools is ready to be on ArchStrike so please add this tool.

**Comment by Torxed** [comment]
All this tool is doing, is check for certain predefined paths and start different services binaries rather than using service scripts etc?

There are a number of issues in the code, such as the use of os.system() to execute commands arbitrarily.

This tool also looks like a "my first project" tool, which in of itself isn't a bad thing. But I wouldn't bring such a tool to any production environment and run it blindly, I'd much rather use systemctl to run my things and/or use the wiki.

The folder structure as well, I had a look at your other project, why use file names that begin with a .? .traceip.php for instance? And the mix of languages?

It all feels like good intentions, but perhaps reinventing the wheel without the new wheel being better doesn't feel like it has a place in production?

Suggestion: Create a AUR package and add it to your own deployment process? That's what I've done with my home cooked DHCP server etc

**Comment by xorond** [comment]
thanks for the insight, i agree completely. you formulated perfectly what i
was thinking. this tool won't be added either.

Anton Hvornum <notifications@github.com> schrieb am Di., 13. Nov. 2018
16:15:

**Comment by Rajkumrdusad** [comment]
Ok and i like your advice and i will try to implement in my all project but actually i am a beginner so i am lerning all that things from web. i don't know how all that things are woking that's there are lots of problem i hope that i will fix all that thing in right manner.
Thank you dear.

**Comment by Torxed** [comment]
@Rajkumrdusad Yea I kind'a noticed this was a beginner (or a few months in to learning programming) who wrote the code :) No offense what so ever, I think it's great that people are actively trying to produce tools and contribute to different projects! So keep it up.

But I wouldn't recommend putting anything that hasn't gone through extensive testing into a stable release or even in a testing repo. Arch Linux has a fantastic AUR system for things like this. And once user adoption is getting bigger, then it might be worth bringing into a main-line repo (like Arch Strike, Arch Linux Community repo etc).

But by all means, keep it up and feel free to pop a link in a comment on this issue to your AUR repo, I don't think anyone would mind :)

@xorond heh, yea I saw your response on the other issue and saw there was a second issue from the same contributor. Did a quick code review and figured the same answer wouldn't hurt here :)
I'm a lurker of Arch Strike, but I like the community and what you're doing here, so, consider this my first contribution.

**Comment by Rajkumrdusad** [comment]
Thank's Dear love you.
