### ISSUE TITLE
GCrypt [Tool Request] v3 with completely new encryption algorithm.

### ISSUE THREAD

**Issue by GasparVardanyan** [ArchStrike/ArchStrike#438]
url: https://github.com/GasparVardanyan/GCrypt

**Comment by Cthulu201** [comment]
Sorry for the delay in replying. This tool seems interesting. What mechanism do you have to prevent brute forcing a lot of passwords until the right file is unencrypted?

**Comment by GasparVardanyan** [comment]
The output file does not have a specific structure: if you enter a wrong password to decrypt the data, the program will not send any error messages, it generates a garbage file, so first the hacker needs to know what type of data is encrypted, and every time the next password is checked, the hacker needs to analyze result. Also, a regular file can be “decrypted” and then restored with encryption.

**Comment by Cthulu201** [comment]
No error messages is interesting. However, running the command file will determine type of data after being unencrypted. So a bash brute force script can expedite that. An anti-brute force mechanism, or generating garbage file with random bogus signatures (just to get 2 ideas out) would add more interest. Otherwise, why would people stop using gpg?

**Comment by GasparVardanyan** [comment]
Ok.

**Comment by GasparVardanyan** [comment]
So the only deffect is that bruteforce can work, but I think that anti-brute force mechanism can't work in client-side, it just works for servers. I think that if the encrypted file and the decryption algorithm is available for users, we can't use any anti-brute force mechanism.

**Comment by GasparVardanyan** [comment]
For AES-128 there are 1.1 x 10^77 possible key combinations and hacker's need 1 billion billion years to brute-force AES-128 (https://www.eetimes.com/document.asp?doc_id=1279619). But there are 256! (256 factorials) possible number of different hashes generated by a password in GCrypt!

**Comment by GasparVardanyan** [comment]
There are more than 10^506 possible number of different hashes generated by a password in GCrypt.

**Comment by Cthulu201** [comment]
Those are just possibilities. Since it's password-based, a hacker just needs 1 password to be successful. We know how bad people are at creating passwords and saving them. gpg offers options, even storing them on a YubiKey instead of a sticky under the keyboard. :)

**Comment by GasparVardanyan** [comment]
Ok.

**Comment by GasparVardanyan** [comment]
So what?

**Comment by Torxed** [comment]
What Cthulu201 is saying is that one "mechanism" to prevent attacks since the users are dumb. So having options to increase security such as hardware tokens are pretty mandatory in this day and age to make something a viable option.
Otherwise you're better off sticking to proven methods with surrounding backup mechanisms and proven implementions.

Especially the last thing is important, a new algorithm needs to go through great lengths of scrutiny before it's implemented I would think.

**Comment by GasparVardanyan** [comment]
GCrypt is open-source, the decryption algorithm is available, so hacker can broke any anti brute force mechanism. I usually do something like **gcrypt -e "\`echo myPassword | base64\`" ifile ofile** for brute force safe encryption.

**Comment by Cthulu201** [comment]
Redundant functionality; gnupg offers same and additional options

**Comment by GasparVardanyan** [comment]
Ok, thank you.
